services:
#    inzynier_app.example:
#        class: Inzynier\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    path.locator:
        class: Inzynier\AppBundle\Services\PathLocator
        arguments: [@request_stack]
        
    geolocator:
        class: Inzynier\AppBundle\Services\Geolocator
        arguments: [@ivory_google_map.map.builder, @doctrine, @router]
        
    friends.service:
        class: Inzynier\AppBundle\Services\FriendsService
        arguments: [@doctrine]
        
    image_type_extension:
        class: Inzynier\AppBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }
            
    category.service:
        class: Inzynier\AppBundle\Services\CategoryService
        arguments: [@router]
        
    twig.url_extension:
        class: Inzynier\AppBundle\Twig\UrlExtension
        tags:
            - { name: twig.extension }
            
    inzynier.language.kernel_request_listener:
        class: Inzynier\AppBundle\Listeners\LanguageListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
            
    inzynier.logged_locale_listener:
        class: Inzynier\AppBundle\Listeners\LoggedLocaleListener
        calls:
            - [ setSession, [@session] ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }